### PR TITLE
fix: race condition crash

### PR DESCRIPTION
**Pull request by arthurgeron**
Doing `getProduct` on iOS would sometimes cause a crash due to a racing condition. This fixes it.
Basically this change makes the products' store and listeners thread-safe.

### CODE REVIEW

**Comment by matthargett** [comment]
can you reproduce the crash in a unit/integration test, that fails without the fix and passes with the fix?

**Comment by arthurgeron** [comment]
> can you reproduce the crash in a unit/integration test, that fails without the fix and passes with the fix?

I'll try to, but I can't give an ETA,  although since getProduct is async, trying to access/write in rapid sequence will inevitably lead to a crash due to a racing condition, which does not occur on Android.

I'll also revert my local changes so I can post the crash logs here.

**Comment by arthurgeron-work** [comment]
> can you reproduce the crash in a unit/integration test, that fails without the fix and passes with the fix?

With the current testing structure, it's impossible to reproduce this crash within unit/integration tests.

**Review by hyochan — APPROVED** [review]
I haven't been able to thoroughly test the changes made in this PR, but trusting ChatGPT's review seems like a good idea

Screenshot 2023-11-01 at 5 45 50 AM

**Comment by arthurgeron-work** [comment]
@hyochan That's a great way of approaching code review on this scenario. Do you mind sharing which format you've used to show code changes to ChatGPT?

**Comment by geroale** [comment]
Hello, this pull didn't fix the problem for us. We are still getting https://github.com/dooboolab-community/react-native-iap/issues/1696

**Comment by Yann-prak** [comment]
@geroale The fix was only on the `RNIapIosSk2.swift` file. If you are still using the STOREKIT1 option like I do, the error occurs on the file `RNIapIos.swift`. You have to apply the same fix applied in the commit. I'm not a swift guy so I don't really know how to fix the thread safety for Storekit 1 😕

**Comment by arthurgeron-work** [comment]
> @geroale The fix was only on the `RNIapIosSk2.swift` file. If you are still using the STOREKIT1 option like I do, the error occurs on the file `RNIapIos.swift`. You have to apply the same fix applied in the commit. I'm not a swift guy so I don't really know how to fix the thread safety for Storekit 1 😕

@geroale @Yann-prak  I'd like to help but I need more stack traces, If it's the same error as #1696 you could post there, or create a new issue if it's different. 

A workaround I had found for my crashes was to never run more than one getProducts or getSubscriptions call at the same time, essentially adding a loading state.

**Comment by arthurgeron** [comment]
@geroale @Yann-prak  I've done a somewhat similar fix to Store Kit 1 code.

**Comment by geroale** [comment]
@arthurgeron Thank you. We had also other concurrency problems in Store Kit 1 by accessing `promisesByKey` in the method `resolvePromises`. Because of this, we wrapped `resolvePromises` with `myQueue.sync` https://github.com/Spicy-Sparks/react-native-iap/blob/main/ios/RNIapIos.swift

From what I'm seeing, your and our changes are compatible, but is there a better way to integrate them, maybe reworking our ones?

**Comment by arthurgeron** [comment]
@geroale Possibly better to bring over your changes, I'll take a look and try later!

**Comment by Yann-prak** [comment]
@arthurgeron you can find a full discussion there #2550 with some stack traces.

Yesterday I've done a similar fix with a ProductStore in local and it was working. I did the same patch as @geroale too. I had some memory issues but I'm not sure if it was linked to the patches or to something else as I did not develop in swift for a long time now. I can share my code if needed.

**Comment by marf** [comment]
> @geroale Possibly better to bring over your changes, I'll take a look and try later!

@arthurgeron we tested our changes at https://github.com/Spicy-Sparks/react-native-iap/blob/main/ios/RNIapIos.swift and the concurrency crashes seem to have disappeared.

**Comment by eight-buddha** [comment]
I confirm that the @geroale  fix works. I don’t understand why one application with the same version of the library has no problems, but the other constantly crashes. As I understand it, this fix will still not be added to the library. Currently using 12.13.2 version.

**Pull request merged**
