### PR TITLE
Update appleSk2.ts

### PR DESCRIPTION
**Pull request by yhostc**
fixed issue for #2607 #2461

### CODE REVIEW

**Review by hyochan — CHANGES_REQUESTED** [review]
Could you kindly check on the CI failing?

**Comment by yhostc** [comment]
Yes, I have checked the code changes and it solved the problem I encountered very well. However, the manifest shows that I only changed one JS code and the CI failure occurred in the swift code, which is beyond my knowledge. I would be very grateful if I could get some help from you.
​

**Comment by cervebar** [comment]
> Yes, I have checked the code changes and it solved the problem I encountered very well. However, the manifest shows that I only changed one JS code and the CI failure occurred in the swift code, which is beyond my knowledge. I would be very grateful if I could get some help from you.​

I think it's just because of swift linter, install this on your Mac - https://github.com/realm/SwiftLint and run `swiftlint lint --fix --format --path ios/*.swift --config .swiftlint.yml`

**Comment by yhostc** [comment]
@cervebar It was you who helped me take the first step in swift, thank you very much!

**Comment by harbolaez** [comment]
Any update on this? thanks!

**Comment by yhostc** [comment]
I'm also looking forward to merging the code. @hyochan

**Review by hyochan — APPROVED** [review]
LGTM!

**Pull request merged**
